/*
  Warnings:

  - The values [SELL_INSCRIBE_CONFIRMED,SELL_INSCRIBE_FAILED,CANCEL_INSCRIBE_CONFIRMED,CANCEL_INSCRIBE_FAILED,TRADE_INSCRIBE_CONFIRMED,TRADE_INSCRIBE_FAILED] on the enum `orders_chain_status` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterTable
ALTER TABLE `orders` MODIFY `chain_status` ENUM('PENDING', 'SELL_BLOCK_CONFIRMED', 'SELL_BLOCK_FAILED', 'CANCEL_BLOCK_CONFIRMED', 'CANCEL_BLOCK_FAILED', 'BUY_BLOCK_CONFIRMED', 'BUY_BLOCK_FAILED', 'TRADE_BLOCK_CONFIRMED', 'TRADE_BLOCK_FAILED') NOT NULL DEFAULT 'PENDING';
